# Generated by Django 2.2.1 on 2019-05-14 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField(null=True)),
                ('profilePic', models.ImageField(blank=True, default='static/images/default_profile_icon.jpg', upload_to=None)),
                ('emailConfirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Enter a description of for group')),
                ('idealCount', models.IntegerField(default=1)),
                ('profilePic', models.ImageField(blank=True, default='static/images/default_group_image.png', upload_to=None)),
                ('activities', models.ManyToManyField(help_text='Select the activities for this group', to='PlusOneApp.Activity')),
                ('members', models.ManyToManyField(help_text='Select members of this group', to='PlusOneApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('timeCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('timeOccuring', models.DateTimeField(null=True)),
                ('reccuring', models.BooleanField(default=False)),
                ('howOften', models.CharField(blank=True, choices=[('D', 'Daily'), ('BW', 'Bi-Weekly'), ('W', 'Weekly'), ('F', 'Fortnightly'), ('M', 'Monthly'), ('Q', 'Quaterly'), ('BY', 'Bi-Yearly'), ('Y', 'Yearly')], max_length=11, null=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('activities', models.ManyToManyField(help_text='Select the activities for this group', to='PlusOneApp.Activity')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlusOneApp.Group')),
            ],
        ),
    ]
