# Generated by Django 2.1.3 on 2019-02-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlusOneApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='member',
            new_name='members',
        ),
    ]
