# Generated by Django 2.2.1 on 2019-05-19 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlusOneApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AlterField(
            model_name='event',
            name='activities',
            field=models.ManyToManyField(help_text='Select the activities for this event', to='PlusOneApp.Activity'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('M', 'Member'), ('A', 'Admin'), ('O', 'Owner')], max_length=6, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlusOneApp.Group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlusOneApp.Account')),
            ],
        ),
    ]
