# Generated by Django 2.2.1 on 2019-05-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlusOneApp', '0002_auto_20190521_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlusOneApp.Account'),
        ),
    ]
