# Generated by Django 2.1.3 on 2019-02-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlusOneApp', '0002_auto_20190215_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='currentCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='idealCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='group',
            name='activities',
            field=models.ManyToManyField(help_text='Select the activities for this group', to='PlusOneApp.Activity'),
        ),
    ]
