# Generated by Django 2.1.3 on 2019-02-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlusOneApp', '0003_auto_20190216_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
