# Generated by Django 2.1.3 on 2019-02-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlusOneApp', '0005_auto_20190217_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='age',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
        migrations.AddField(
            model_name='account',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profilePic',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='group',
            name='groupImage',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='firstName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
