# Generated by Django 2.1.3 on 2019-02-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlusOneApp', '0006_auto_20190217_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groupImage',
        ),
    ]
