# Generated by Django 2.1.3 on 2019-02-18 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlusOneApp', '0007_remove_group_groupimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('timeCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('timeOccuring', models.DateTimeField(null=True)),
                ('reccuring', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=500, null=True)),
                ('activities', models.ManyToManyField(help_text='Select the activities for this group', to='PlusOneApp.Activity')),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='location',
        ),
        migrations.RemoveField(
            model_name='group',
            name='reccuring',
        ),
        migrations.RemoveField(
            model_name='group',
            name='timeCreated',
        ),
        migrations.RemoveField(
            model_name='group',
            name='timeOccuring',
        ),
        migrations.AddField(
            model_name='group',
            name='profilePic',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlusOneApp.Group'),
        ),
    ]
