# Generated by Django 2.1.3 on 2019-02-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlusOneApp', '0008_auto_20190218_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='howOften',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('BW', 'Bi-Weekly'), ('W', 'Weekly'), ('F', 'Fortnightly'), ('M', 'Monthly'), ('Q', 'Quaterly'), ('BY', 'Bi-Yearly'), ('Y', 'Yearly')], max_length=11, null=True),
        ),
    ]
