# Generated by Django 2.1.7 on 2019-02-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlusOneApp', '0010_auto_20190226_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='emailConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
