# Generated by Django 2.1.3 on 2019-02-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlusOneApp', '0011_auto_20190221_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lastName',
        ),
    ]
