# Generated by Django 2.1.7 on 2019-02-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlusOneApp', '0013_auto_20190228_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='id',
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
